### PR TITLE
Added: Update blog page date field and date format

### LINKED ISSUE #17: Add timestamp check for blog post order
The blog posts are sorted in reverse chronological order (latest first), but it does not look at the timestam.
If multiple posts are made on the same day, the one with the latest time stamp is not first in line.

Scherm­afbeelding 2024-06-01 om 17 27 39

### PR DESCRIPTION
**Pull request by drikusroor**
I have made changes to the `BlogPage` model to update the `date` field to use `DateTimeField` instead of `DateField`. This change allows for more precise timestamp information for blog posts and a better sort order on the index page. Additionally, I have updated the date format in the `blog_index_page.html` and `blog_page.html` templates to include the time in addition to the date. This change provides more precise timestamp information for blog posts.

Resolves #17

### CODE REVIEW

**Comment by naomi-eliasar** [comment]
If I run this branch I get a TypeError, I don't get that error on main
Scherm­afbeelding 2024-07-23 om 09 30 42

**Comment by naomi-eliasar** [comment]
When I create a new blog post, the time is set to 04:41, it would be nice if it automatically set it to the current time

**Comment by drikusroor** [comment]
> When I create a new blog post, the time is set to 04:41, it would be nice if it automatically set it to the current time

It's probably set to some American time (minutes are correct right?).. 😓

**Comment by naomi-eliasar** [comment]
If I change the time manually, the blog post doesn't show on the home page.
If we shouldn't be able to change the time manually, it might be better to not show the time selector

**Comment by drikusroor** [comment]
> If I change the time manually, the blog post doesn't show on the home page. If we shouldn't be able to change the time manually, it might be better to not show the time selector

Yeah, you might have put the time in the future then. What happens if you set the correct time, but on yesterday's date?

**Comment by naomi-eliasar** [comment]
> > When I create a new blog post, the time is set to 04:41, it would be nice if it automatically set it to the current time
> 
> It's probably set to some American time (minutes are correct right?).. 😓

Maybe yes, the minutes are correct indeed.
But when I check the time in the console, firefox does seem to know it's 11:56, but on the wagtail page it still shows the 04:56. 
I don't have a vpn on 

You don't experience this issue?

Scherm­afbeelding 2024-07-23 om 11 56 29

**Comment by drikusroor** [comment]
> > > When I create a new blog post, the time is set to 04:41, it would be nice if it automatically set it to the current time
> > 
> > 
> > It's probably set to some American time (minutes are correct right?).. 😓
> 
> Maybe yes, the minutes are correct indeed. But when I check the time in the console, firefox does seem to know it's 11:56, but on the wagtail page it still shows the 04:56. I don't have a vpn on
> 
> You don't experience this issue?
> Scherm­afbeelding 2024-07-23 om 11 56 29

Hmmm... no I don't have that problem :P Maybe we can merge it and deploy it to the test environment and see how it behaves there?

afbeelding

**Pull request merged**
