### PR TITLE
Refactor: Improve styling of blog filter bar

### PR DESCRIPTION
**Pull request by drikusroor**

### CODE REVIEW

**Comment by naomi-eliasar** [comment]
The search & reset button don't work as expected

1.  They appear disabled, but both are clickable and respond
2. If I fill in the searchbar, they remain the look of disabled
3. Only if I click outside the searchbar after filling it, the search button appears available. But the reset button at that point also should appear available.
4. Having to click outside the searchbar to make the search&reset button available seems counter intuitive, and won't work very well on mobile screens

**Comment by naomi-eliasar** [comment]
On mobile screen it looks ugly and the resetbutton falls of the screen

Scherm­afbeelding 2024-08-01 om 14 37 34

**Comment by drikusroor** [comment]
> The search & reset button don't work as expected
> 
>     1. They appear disabled, but both are clickable and respond
> 
>     2. If I fill in the searchbar, they remain the look of disabled
> 
>     3. Only if I click outside the searchbar after filling it, the search button appears available. But the reset button at that point also should appear available.
> 
>     4. Having to click outside the searchbar to make the search&reset button available seems counter intuitive, and won't work very well on mobile screens

Haveth thou a screenshot for me?

**Comment by naomi-eliasar** [comment]
> > The search & reset button don't work as expected
> > ```
> > 1. They appear disabled, but both are clickable and respond
> > 
> > 2. If I fill in the searchbar, they remain the look of disabled
> > 
> > 3. Only if I click outside the searchbar after filling it, the search button appears available. But the reset button at that point also should appear available.
> > 
> > 4. Having to click outside the searchbar to make the search&reset button available seems counter intuitive, and won't work very well on mobile screens
> > ```
> 
> Haveth thou a screenshot for me?

Sim, a video. But it's too big so a [wetransfer link](https://we.tl/t-xMaPDDIgSS)

**Comment by drikusroor** [comment]
> > > The search & reset button don't work as expected
> > > ```
> > > 1. They appear disabled, but both are clickable and respond
> > > 
> > > 2. If I fill in the searchbar, they remain the look of disabled
> > > 
> > > 3. Only if I click outside the searchbar after filling it, the search button appears available. But the reset button at that point also should appear available.
> > > 
> > > 4. Having to click outside the searchbar to make the search&reset button available seems counter intuitive, and won't work very well on mobile screens
> > > ```
> > 
> > 
> > Haveth thou a screenshot for me?
> 
> Sim, a video. But it's too big so a [wetransfer link](https://we.tl/t-xMaPDDIgSS)

I think I fixed most issues

**Comment by drikusroor** [comment]
> On mobile screen it looks ugly and the resetbutton falls of the screen. I think it will look better if the different filters are below each other on mobile screens
> Scherm­afbeelding 2024-08-01 om 14 37 34

I fixed this too I think

**Comment by naomi-eliasar** [comment]
> > On mobile screen it looks ugly and the resetbutton falls of the screen. I think it will look better if the different filters are below each other on mobile screens
> > Scherm­afbeelding 2024-08-01 om 14 37 34
> 
> I fixed this too I think

I like the look of the two buttons together on the right side of the screen better. I thinks it looks a little bit off for the smallest screen sizes now

Scherm­afbeelding 2024-08-01 om 15 48 20

Scherm­afbeelding 2024-08-01 om 15 48 27

**Comment by naomi-eliasar** [comment]
> > > > The search & reset button don't work as expected
> > > > ```
> > > > 1. They appear disabled, but both are clickable and respond
> > > > 
> > > > 2. If I fill in the searchbar, they remain the look of disabled
> > > > 
> > > > 3. Only if I click outside the searchbar after filling it, the search button appears available. But the reset button at that point also should appear available.
> > > > 
> > > > 4. Having to click outside the searchbar to make the search&reset button available seems counter intuitive, and won't work very well on mobile screens
> > > > ```
> > > 
> > > 
> > > Haveth thou a screenshot for me?
> > 
> > 
> > Sim, a video. But it's too big so a [wetransfer link](https://we.tl/t-xMaPDDIgSS)
> 
> I think I fixed most issues

You did 👍🏻

**Pull request merged**
