### PR TITLE
Update author display logic and add Python files to Tailwind CSS config

### LINKED ISSUE #28: Create an authors page
Create an overview page of the authors/reisgezelschap. 

It can be similair to the ohayo-goededagu page.
So cards for each traveler with a picture, name, age, profession and a short story/sentence that the travelers can edit themselves in the admin panel

From the authors page, if you click on a card of an author, you will go to the filtered blog post page that shows all posts by that author ( #29 )

### PR DESCRIPTION
**Pull request by drikusroor**
So this PR adds the AuthorIndexPage and the AuthorPage and adds an "author" property to every BlogPage (post) that is required to be set. Similar to Wordpress. There is some AI-generated styling (based off styling of BlogIndexPage and BlogPage) but it could be done a bit better I think. Also, I moved the display author name and display avatar to `user_tags.py`, which is pretty neat.

Of course, when you want to test this, don't forget to run `bin/manage migrate` :D

Resolves #28

### CODE REVIEW

**Comment by naomi-eliasar** [comment]
I've created an authors index page and added a couple authors to it, but they don't show up on the authors page

admin overview of the authors index page:
Scherm­afbeelding 2024-07-25 om 10 04 40

authors index page:
Scherm­afbeelding 2024-07-25 om 10 04 50

authors page:
Scherm­afbeelding 2024-07-25 om 10 05 00

**Comment by naomi-eliasar** [comment]
Is it possible to have the logged in user automatically set as the author of a blog post?

**Comment by naomi-eliasar** [comment]
I know this wasn't in the issue, but I would expect clicking on the name/avatar in a blog post will also bring me to that authors page of that specific author

Scherm­afbeelding 2024-07-25 om 10 09 06

**Comment by naomi-eliasar** [comment]
It would be convenient if there was a button on the homepage to bring you to the authors index page

**Comment by naomi-eliasar** [comment]
The blog post grid looks different on the authors page than it does on the homepage. On the homepage there is more yellow than on the authors page.
I think it will look better if it looks the same

Authors page:
Scherm­afbeelding 2024-07-25 om 10 19 28

Home/blog page:
Scherm­afbeelding 2024-07-25 om 10 18 33

**Comment by naomi-eliasar** [comment]
I think it will look better if we just put the authors avatar on the homescreen for each post. Now it looks a little crazy end busy because they are all displaying differently depending on the length of the authors name, blog title and intro text

Scherm­afbeelding 2024-07-25 om 10 27 40

**Comment by naomi-eliasar** [comment]
Am I understanding it correctly that any user can be selected as the author of a post?
That might become an annoying thing in the future when there are many users

**Comment by naomi-eliasar** [comment]
In the selection field of the author, is it possible to change the name to the 'first name + last name' instead of the users login username?

**Comment by drikusroor** [comment]
> I've created an authors index page and added a couple authors to it, but they don't show up on the authors page
> 
> admin overview of the authors index page: Scherm­afbeelding 2024-07-25 om 10 04 40
> 
> authors index page: Scherm­afbeelding 2024-07-25 om 10 04 50
> 
> authors page: Scherm­afbeelding 2024-07-25 om 10 05 00

For authors to show up in the author page they need to be the owner of at least one post

**Comment by drikusroor** [comment]
> Am I understanding it correctly that any user can be selected as the author of a post? That might become an annoyingly long list in the future when there are many users. Maybe it's possible to use roles for users again, so we can only show those users in the author select field that have the role 'author' or 'admin' or something

Yeah probably a good idea. But to avoid scope creep let's make this a separate issue.

**Comment by drikusroor** [comment]
> It would be convenient if there was a button on the homepage to bring you to the authors index page. Now the only way to go there is to type in the url

You can do this using the _Show in menus_ checkbox in the _Promote_ tab of the Authors page:

afbeelding

**Comment by drikusroor** [comment]
> Is it possible to have the logged in user/owner of the post automatically selected as the author of a blog post?

This should already happen (it happens for me at least 😄 )

**Pull request merged**
